name: 'flower'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Minecraft Version'
        required: true
        default: 'latest'
        type: string
jobs:
  watering-and-bloom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - run: pip install -r requirements.txt
      - run: bash load-jar.sh
      - run: python main.py --version ${{ inputs.version }}
        env:
          github-username: boon4681
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: boon4681/itemsflower